language: node_js
node_js:
- stable
- '6'
- '4'
before_install:
- openssl aes-256-cbc -K $encrypted_1658394769ee_key -iv $encrypted_1658394769ee_iv
  -in howtomcserver_travis_github_deploy_key.enc -out howtomcserver_travis_github_deploy_key
  -d
- chmod 600 howtomcserver_travis_github_deploy_key
- eval $(ssh-agent -s)
- ssh-add howtomcserver_travis_github_deploy_key
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
script:
- yarn build
- yarn deploy
